// Generated by scripts/assets/build.ts — do not edit.
export const ASSET_CREDITS = {
  fluent: {
    name: 'Fluent Emoji (3D)',
    author: 'Microsoft Corporation',
    license: 'MIT',
    source: 'https://github.com/microsoft/fluentui-emoji',
    notice:
      'MIT License\n\nCopyright (c) Microsoft Corporation.\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and\nassociated documentation files (the "Software"), to deal in the Software without restriction,\nincluding without limitation the rights to use, copy, modify, merge, publish, distribute,\nsublicense, and/or sell copies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or\nsubstantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT\nNOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,\nDAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT\nOF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
    count: 78,
  },
  noto: {
    name: 'Noto Emoji animations',
    author: 'Google LLC',
    license: 'CC BY 4.0',
    source: 'https://googlefonts.github.io/noto-emoji-animation/',
    licenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    notice:
      'Animated emoji by Google (Noto Emoji Animation), licensed under Creative Commons Attribution 4.0 International. Frames were resized and re-encoded; no other changes were made.',
    count: 20,
  },
} as const;
