import type { QuestionLanguage } from './enums';

/**
 * Word lists behind the audit heuristics. They are deliberately small and conservative: a match
 * never rejects a question on its own (profanity aside), it asks an editor to look. All entries
 * are written already folded (lower case, no diacritics) because they are compared against
 * `foldKey` output.
 */
type ByLanguage<T> = Record<QuestionLanguage, T>;

/** Openers that read like a presenter, not like a question (rubric §4: fake conversational filler). */
export const FILLER_OPENERS: ByLanguage<readonly string[]> = {
  tr: [
    'biliyor muydunuz',
    'biliyor musunuz',
    'merhaba',
    'selam',
    'haydi',
    'hadi bakalim',
    'peki',
    'sevgili',
    'dikkat',
    'hazir misiniz',
    'sira sizde',
    'ilginc bir',
    'eglenceli bir',
  ],
  en: ['did you know', 'let s see', 'hey', 'hello', 'fun fact', 'ready', 'get ready'],
};

/** Phrasing typical of generated copy (rubric §6: "does this feel like it came from a language model?"). */
export const SLOP_STRONG: ByLanguage<readonly string[]> = {
  tr: [
    'sasirtici bir sekilde',
    'buyuleyici',
    'cok yonlu',
    'zengin kulturel',
    'kulturel mirasi',
    'tarihin tozlu',
    'tarihin derinliklerinde',
    'gunumuz dunyasinda',
    'gelisen dunyada',
    'cigir acan',
    'devrim niteliginde',
    'onemli bir rol oynamistir',
    'onemli bir yere sahiptir',
  ],
  en: [
    'delve',
    'tapestry',
    'rich cultural heritage',
    'in the realm of',
    'testament to',
    'pivotal role',
    'ever evolving',
  ],
};
export const SLOP_WEAK: ByLanguage<readonly string[]> = {
  tr: [
    'kapsamli',
    'dikkat cekici',
    'essiz',
    'unutulmaz',
    'sira disi',
    'hic suphesiz',
    'tarih boyunca',
  ],
  en: ['fascinating', 'renowned', 'remarkable', 'iconic', 'legendary', 'unforgettable'],
};

/** Words that should never be written without their diacritics in Turkish text (ASCII-typed copy). */
export const ASCII_FOLDED_TURKISH: ReadonlySet<string> = new Set([
  'turkiye',
  'icin',
  'icinde',
  'uzerinde',
  'uzerine',
  'gore',
  'sehir',
  'sehri',
  'ulke',
  'ulkesi',
  'ulkenin',
  'buyuk',
  'kucuk',
  'yuzyil',
  'yuzyilda',
  'dunya',
  'dunyanin',
  'muzik',
  'universite',
  'universitesi',
  'ogrenci',
  'ogretmen',
  'ogrenmek',
  'calisma',
  'uretim',
  'uretici',
  'guney',
  'baskent',
  'baskenti',
  'baskentidir',
  'sanatci',
  'sarkici',
  'soyle',
  'once',
  'yilinda',
  'yilda',
  'yildiz',
  'nufus',
  'nufusu',
  'yuksek',
  'dag',
  'dagi',
  'cikolata',
  'corba',
  'balik',
  'kopek',
  'cocuk',
  'cocuklar',
  'cumhuriyetin',
  'gunes',
  'gokyuzu',
  'kullanilan',
  'kullanilir',
  'olusturan',
  'kurulus',
  'savas',
  'savasi',
  'sampiyon',
  'sampiyonu',
  'olcu',
  'olcusu',
  'yagmur',
  'sicaklik',
  // typed with a plain capital I, which Turkish lower-cases to a dotless ı
  'ıstanbul',
  'ızmir',
  'ıspanya',
  'ıtalya',
  'ıngiltere',
  'ırlanda',
  'ısvec',
  'ısvicre',
  'ıran',
  'ısrail',
  'ızlanda',
]);

/** Words that mark a negated stem ("which of these is NOT …"). */
export const NEGATIVE_WORDS: ByLanguage<ReadonlySet<string>> = {
  tr: new Set([
    'degildir',
    'degil',
    'olmayan',
    'olmamis',
    'haric',
    'disinda',
    'yanlistir',
    'yanlis',
    'yoktur',
    'bulunmaz',
    'yapilmamistir',
  ]),
  en: new Set(['not', 'except', 'false', 'incorrect', 'excluding']),
};

/** Phrases that tie a question to "now" (matched against the space-joined folded stem). */
export const TEMPORAL_PHRASES: ByLanguage<readonly string[]> = {
  tr: [
    'su an',
    'su anda',
    'su anki',
    'simdi',
    'simdiki',
    'bugun',
    'bugunku',
    'gunumuzde',
    'gunumuzdeki',
    'halen',
    'hala',
    'guncel',
    'mevcut',
    'en son',
    'en yeni',
    'son zamanlarda',
    'yakin zamanda',
    'gecen yil',
    'bu yil',
    'gelecek yil',
    'hali hazirda',
  ],
  en: [
    'current',
    'currently',
    'incumbent',
    'nowadays',
    'today',
    'right now',
    'latest',
    'newest',
    'recently',
    'this year',
    'last year',
    'next year',
    'at present',
    'present day',
    'as of',
  ],
};

export const ABSOLUTE_WORDS: ByLanguage<ReadonlySet<string>> = {
  tr: new Set(['kesinlikle', 'daima', 'asla', 'mutlaka']),
  en: new Set(['always', 'never', 'definitely', 'absolutely', 'undoubtedly']),
};

/** Topics a family party game wants an editor to look at before they reach the TV. */
export const SENSITIVE_STEMS: ByLanguage<readonly string[]> = {
  tr: [
    'intihar',
    'tecavuz',
    'cinsel',
    'pornograf',
    'soykirim',
    'katliam',
    'nazi',
    'hitler',
    'holokost',
    'uyusturucu',
    'kokain',
    'eroin',
    'esrar',
    'irkci',
    'terorist',
  ],
  en: [
    'suicide',
    'rape',
    'sexual',
    'porn',
    'genocide',
    'massacre',
    'nazi',
    'hitler',
    'holocaust',
    'cocaine',
    'heroin',
    'racist',
    'terrorist',
  ],
};

/** "All of the above" in every shape we have seen (matched against the folded option). */
export const ALL_OR_NONE =
  /^(?:hepsi|hicbiri|hicbirisi|bunlarin hepsi|bunlarin hicbiri|yukaridakilerin (?:hepsi|hicbiri)|yukaridakilerden hicbiri|ikisi de|her ikisi de|ikisi de dogru|hepsi dogru|hepsi yanlis|[a-f] ve [a-f]|all of the above|none of the above|both of the above|both)(?: |$)/u;

/** Text that proves a row is a template or leftover, not a question. */
export const PLACEHOLDER_PATTERN =
  /lorem ipsum|\btodo\b|\btbd\b|\bxxx+\b|\bn\/a\b|\{\{|\}\}|\[\.\.\.\]|<\/?[a-z][^>]*>|\b(?:secenek|option|answer|cevap) [a-f]\b|\bornek soru\b|\bsample question\b/iu;

/** Mojibake sequences produced by decoding UTF-8 Turkish as Latin-1 / Windows-1252. */
export const MOJIBAKE = [
  'Ã¼',
  'Ã¶',
  'Ã§',
  'Ã–',
  'Ãœ',
  'Ã‡',
  'Ä±',
  'Ä°',
  'ÄŸ',
  'Äž',
  'ÅŸ',
  'Åž',
  'â€™',
  'â€œ',
  'â€',
  'Â ',
  '�',
] as const;

/**
 * Category keyword stems for the "category mismatch" smell. A stem ending in `*` matches any word
 * that starts with it; others must match a whole word. Only stems of five letters or more use `*`.
 */
export const CATEGORY_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  history: [
    'savas*',
    'sultan*',
    'padisah*',
    'imparator*',
    'osmanli*',
    'selcuk*',
    'bizans*',
    'antlasma*',
    'ihtilal*',
    'devrim*',
    'fetih*',
    'kurtulus*',
    'medeniyet*',
    'uygarlik*',
    'firavun*',
    'hitit*',
    'sumer*',
  ],
  geography: [
    'baskent*',
    'nehir*',
    'nehri',
    'okyanus*',
    'yarimada*',
    'kita',
    'kitasi',
    'yuzolcum*',
    'iklim*',
    'bogaz*',
    'korfez*',
    'vadi*',
    'ova',
    'platosu',
    'nufus*',
  ],
  science: [
    'atom*',
    'molekul*',
    'element*',
    'enerji*',
    'gezegen*',
    'galaksi*',
    'fizik*',
    'kimya*',
    'biyoloji*',
    'hucre*',
    'elektron*',
    'proton*',
    'yercekimi*',
    'manyetik*',
    'virus*',
    'bakteri*',
  ],
  nature: [
    'hayvan*',
    'bitki*',
    'agac*',
    'cicek*',
    'memeli*',
    'surungen*',
    'bocek*',
    'orman*',
    'yaprak*',
    'tohum*',
    'habitat*',
    'ekosistem*',
  ],
  technology: [
    'bilgisayar*',
    'yazilim*',
    'donanim*',
    'internet*',
    'islemci*',
    'algoritma*',
    'uygulama*',
    'siber*',
    'batarya*',
    'yapay',
    'robot*',
    'akilli',
  ],
  'art-culture': [
    'ressam*',
    'heykel*',
    'tablo*',
    'sergi*',
    'muze*',
    'mimar*',
    'tiyatro*',
    'sanatci*',
    'seramik*',
    'minyatur*',
    'orkestra*',
    'bale',
  ],
  literature: [
    'roman*',
    'sair*',
    'yazar*',
    'siir*',
    'hikaye*',
    'edebiyat*',
    'destan*',
    'mesnevi*',
    'divan*',
    'kitap*',
    'oykucu*',
  ],
  'cinema-tv': [
    'film*',
    'dizi',
    'dizisi',
    'yonetmen*',
    'oyuncu*',
    'senaryo*',
    'sinema*',
    'oscar*',
    'televizyon*',
    'aktor*',
    'aktris*',
    'animasyon*',
    'belgesel*',
  ],
  music: [
    'sarki*',
    'sarkici*',
    'album*',
    'besteci*',
    'konser*',
    'gitar*',
    'piyano*',
    'keman*',
    'melodi*',
    'enstruman*',
    'orkestra*',
    'nota',
  ],
  gaming: [
    'konsol*',
    'playstation*',
    'xbox*',
    'nintendo*',
    'mario*',
    'zelda*',
    'minecraft*',
    'fortnite*',
    'oyun',
    'oyunu',
    'oyunun',
    'steam*',
    'esport*',
  ],
  sports: [
    'futbol*',
    'basketbol*',
    'voleybol*',
    'sampiyon*',
    'olimpiyat*',
    'turnuva*',
    'antrenor*',
    'stadyum*',
    'kaleci*',
    'tenis*',
    'atletizm*',
    'madalya*',
  ],
  'food-drink': [
    'yemek*',
    'corba*',
    'tatli*',
    'icecek*',
    'peynir*',
    'baharat*',
    'mutfak*',
    'yogurt*',
    'zeytinyag*',
    'kebap*',
    'baklava*',
    'sebze*',
    'meyve*',
  ],
  'mythology-folklore': [
    'tanri*',
    'mitoloji*',
    'efsane*',
    'masal*',
    'titan*',
    'olimpos*',
    'ejderha*',
    'folklor*',
    'zeus',
    'odin',
    'athena',
    'poseidon',
  ],
  'language-words': [
    'kelime*',
    'sozcuk*',
    'deyim*',
    'atasozu',
    'atasozleri',
    'alfabe*',
    'sozluk*',
    'imla',
    'hece*',
    'fiil*',
    'sifat*',
    'es anlamli',
    'zit anlamli',
  ],
  'business-economy': [
    'sirket*',
    'ekonomi*',
    'borsa*',
    'enflasyon*',
    'faiz*',
    'banka*',
    'yatirim*',
    'ihracat*',
    'ithalat*',
    'vergi*',
    'hisse*',
    'girisimci*',
  ],
  'math-logic': [
    'toplam*',
    'carpim*',
    'ucgen*',
    'daire*',
    'denklem*',
    'faktoriyel*',
    'yuzde*',
    'kesir*',
    'olasilik*',
    'geometri*',
    'cebir*',
    'ardisik*',
    'rakam*',
    'basamak*',
  ],
};
