/**
 * Downloads the upstream emoji art listed in manifest.ts, optimises it and writes it to
 * apps/web/src/assets. The outputs are committed, so builds never touch the network; run
 * `pnpm assets:build` only to refresh or extend the set.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import {
  ANIMATIONS,
  AVATARS,
  LICENSES,
  STICKERS,
  fluentUrl,
  notoUrl,
  type FluentAsset,
  type NotoAnimation,
} from './manifest.ts';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const CACHE = join(ROOT, 'scripts/assets/.cache');
const OUT = join(ROOT, 'apps/web/src/assets');

function ensure(directory: string): void {
  mkdirSync(directory, { recursive: true });
}

async function download(url: string, cacheName: string): Promise<Buffer> {
  const cached = join(CACHE, cacheName);
  if (existsSync(cached)) return readFileSync(cached);
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  ensure(dirname(cached));
  writeFileSync(cached, bytes);
  return bytes;
}

interface Written {
  path: string;
  bytes: number;
}

async function buildStatic(
  group: 'avatars' | 'stickers',
  assets: readonly FluentAsset[],
  size: number,
): Promise<Written[]> {
  const written: Written[] = [];
  ensure(join(OUT, group));
  for (const asset of assets) {
    const source = await download(fluentUrl(asset), `fluent/${asset.id}.png`);
    const output = await sharp(source)
      .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .webp({ quality: 90, alphaQuality: 95, effort: 6 })
      .toBuffer();
    const path = join(OUT, group, `${asset.id}.webp`);
    writeFileSync(path, output);
    written.push({ path, bytes: output.length });
  }
  return written;
}

/**
 * Noto animations ship 30 fps frames at 512 px (150–600 KiB). Every second frame is kept (the
 * motion stays smooth at 15 fps for emoji-style art) and the frames are re-encoded at the display
 * size, which brings each file to roughly 40–80 KiB.
 */
async function buildAnimations(
  assets: readonly NotoAnimation[],
  defaultSize: number,
): Promise<Written[]> {
  const written: Written[] = [];
  ensure(join(OUT, 'animated'));
  for (const asset of assets) {
    const size = asset.size ?? defaultSize;
    const source = await download(notoUrl(asset), `noto/${asset.codepoint}.webp`);
    const meta = await sharp(source, { animated: true }).metadata();
    const pages = meta.pages ?? 1;
    const delay = meta.delay?.[0] ?? 30;
    const { data, info } = await sharp(source, { animated: true })
      .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    const frameHeight = info.height / pages;
    const frameBytes = info.width * frameHeight * info.channels;
    const kept: Buffer[] = [];
    for (let frame = 0; frame < pages; frame += 2)
      kept.push(data.subarray(frame * frameBytes, (frame + 1) * frameBytes));
    const output = await sharp(Buffer.concat(kept), {
      raw: {
        width: info.width,
        height: frameHeight * kept.length,
        channels: 4,
        pageHeight: frameHeight,
      },
    })
      .webp({
        quality: 50,
        alphaQuality: 20,
        effort: 6,
        loop: 0,
        delay: kept.map(() => delay * 2),
      })
      .toBuffer();
    const path = join(OUT, 'animated', `${asset.id}.webp`);
    writeFileSync(path, output);
    written.push({ path, bytes: output.length });
  }
  return written;
}

function kib(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} KiB`;
}

const avatars = await buildStatic('avatars', AVATARS, 256);
const stickers = await buildStatic('stickers', STICKERS, 192);
const animations = await buildAnimations(ANIMATIONS, 128);

for (const [label, list] of [
  ['avatars', avatars],
  ['stickers', stickers],
  ['animated', animations],
] as const) {
  const total = list.reduce((sum, item) => sum + item.bytes, 0);
  const largest = Math.max(...list.map((item) => item.bytes));
  process.stdout.write(
    `${label}: ${list.length} files, ${kib(total)} total, largest ${kib(largest)}\n`,
  );
}

const credits = {
  fluent: { ...LICENSES.fluent, count: avatars.length + stickers.length },
  noto: { ...LICENSES.noto, count: animations.length },
};
writeFileSync(
  join(OUT, 'credits.generated.ts'),
  `// Generated by scripts/assets/build.ts — do not edit.\nexport const ASSET_CREDITS = ${JSON.stringify(credits, null, 2)} as const;\n`,
);
writeFileSync(
  join(OUT, 'NOTICE.md'),
  `# Third-party artwork\n\n## ${LICENSES.fluent.name} — ${LICENSES.fluent.license}\n\n${LICENSES.fluent.source}\n\n\`\`\`\n${LICENSES.fluent.notice}\n\`\`\`\n\n## ${LICENSES.noto.name} — ${LICENSES.noto.license}\n\n${LICENSES.noto.source}\n\n${LICENSES.noto.notice}\n\nLicence: ${LICENSES.noto.licenseUrl}\n`,
);
